-- ============================================
-- Johor Food Database - Complete Installation Script
-- Generated by: export_to_sql.py
-- Generated at: 2026-08-26 03:25:27
-- Total records: 2
-- Database: johor_food_db
-- ============================================

-- ============================================
-- 1. Create Database (If Not Exists)
-- ============================================
CREATE DATABASE IF NOT EXISTS `johor_food_db` 
    CHARACTER SET utf8mb4 
    COLLATE utf8mb4_unicode_ci;

USE `johor_food_db`;

-- ============================================
-- 2. Drop Existing Table (Proceed with caution; comment out to keep existing data)
-- ============================================
DROP TABLE IF EXISTS `johor_food`;

-- ============================================
-- 3. Create Table Structure
-- ============================================
CREATE TABLE `johor_food` (
    -- Primary Key,
    `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'Primary Key ID',
,
    -- Basic Information,
    `name` VARCHAR(100) NOT NULL COMMENT 'Restaurant/Food Name',
    `cuisine` VARCHAR(50) DEFAULT NULL COMMENT 'Cuisine/Flavor Category',
    `price` VARCHAR(50) DEFAULT NULL COMMENT 'Price Range or Avg Spending',
    `rating` DECIMAL(3,2) DEFAULT NULL COMMENT 'Rating (Out of 5.0)',
    `url` VARCHAR(500) DEFAULT NULL COMMENT 'Amap / Map Link',
    `hours` VARCHAR(200) DEFAULT NULL COMMENT 'Business Hours',
    `notes` TEXT DEFAULT NULL COMMENT 'Recommended Dishes / Notes',
,
    -- System Fields,
    `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Created At',
    `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Updated At',
,
    -- Indexes,
    PRIMARY KEY (`id`),
    INDEX `idx_name` (`name`),
    INDEX `idx_cuisine` (`cuisine`),
    INDEX `idx_rating` (`rating`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Johor Food Recommendations Table'

-- ============================================
-- 4. Import Data
-- ============================================
BEGIN;

INSERT INTO `johor_food` (`name`, `cuisine`, `price`, `rating`, `url`, `hours`, `notes`) VALUES
    ('示例餐厅', '中餐', '¥50-100', '4.5', 'https://example.com', '周一-周日 11:00-21:00', '示例条目：这是一个用来展示 CSV 格式的示例行。'),
    ('RunningMan Korea Restaurant', 'BBQ', 'RM40-60', '4.4', 'https://maps.app.goo.gl/SLcFTksQKvBHkXvy6?g_st=ic', '10:00-22:00', 'Kimchi soup');

COMMIT;


-- ============================================
-- 5. Data Validation Queries (Optional)
-- ============================================

-- Check total imported records
SELECT COUNT(*) AS total_records FROM `johor_food`;

-- Statistics by cuisine
SELECT 
    `cuisine`,
    COUNT(*) AS count,
    ROUND(AVG(`rating`), 2) AS avg_rating
FROM `johor_food`
WHERE `cuisine` IS NOT NULL
GROUP BY `cuisine`
ORDER BY count DESC;

-- High-rated recommendations (4.8+)
SELECT `name`, `cuisine`, `rating`, `price`, `notes`
FROM `johor_food`
WHERE `rating` >= 4.8
ORDER BY `rating` DESC;

-- Group by price range
SELECT 
    CASE 
        WHEN `price` REGEXP '^¥[0-9]+$' AND CAST(REPLACE(`price`, '¥', '') AS UNSIGNED) < 30 THEN 'Under ¥30'
        WHEN `price` REGEXP '^¥[0-9]+$' AND CAST(REPLACE(`price`, '¥', '') AS UNSIGNED) BETWEEN 30 AND 60 THEN '¥30-60'
        WHEN `price` REGEXP '^¥[0-9]+$' AND CAST(REPLACE(`price`, '¥', '') AS UNSIGNED) BETWEEN 60 AND 100 THEN '¥60-100'
        WHEN `price` REGEXP '^¥[0-9]+$' AND CAST(REPLACE(`price`, '¥', '') AS UNSIGNED) > 100 THEN 'Above ¥100'
        ELSE 'TBD'
    END AS price_range,
    COUNT(*) AS count
FROM `johor_food`
GROUP BY price_range
ORDER BY price_range;



-- ============================================
-- 6. Create Views (For frequent queries)
-- ============================================

-- Create high-rated food view
CREATE OR REPLACE VIEW `v_high_rating_food` AS
SELECT 
    `id`, `name`, `cuisine`, `price`, `rating`, `notes`
FROM `johor_food`
WHERE `rating` >= 4.5
ORDER BY `rating` DESC;

-- Create cuisine stats view
CREATE OR REPLACE VIEW `v_cuisine_stats` AS
SELECT 
    `cuisine`,
    COUNT(*) AS total_count,
    ROUND(AVG(`rating`), 2) AS avg_rating,
    MAX(`rating`) AS max_rating,
    MIN(`rating`) AS min_rating
FROM `johor_food`
WHERE `cuisine` IS NOT NULL
GROUP BY `cuisine`
ORDER BY total_count DESC;



-- ============================================
-- 7. Create Stored Procedures (For easy data management)
-- ============================================

DELIMITER //

-- Query food by rating range
CREATE PROCEDURE `sp_get_food_by_rating`(
    IN min_rating DECIMAL(3,2),
    IN max_rating DECIMAL(3,2)
)
BEGIN
    SELECT `name`, `cuisine`, `price`, `rating`, `notes`
    FROM `johor_food`
    WHERE `rating` BETWEEN min_rating AND max_rating
    ORDER BY `rating` DESC;
END //

-- Query food by cuisine
CREATE PROCEDURE `sp_get_food_by_cuisine`(
    IN cuisine_name VARCHAR(50)
)
BEGIN
    SELECT `name`, `price`, `rating`, `notes`
    FROM `johor_food`
    WHERE `cuisine` = cuisine_name
    ORDER BY `rating` DESC;
END //

-- Search food (fuzzy search on name and notes)
CREATE PROCEDURE `sp_search_food`(
    IN keyword VARCHAR(100)
)
BEGIN
    SELECT `name`, `cuisine`, `price`, `rating`, `notes`
    FROM `johor_food`
    WHERE `name` LIKE CONCAT('%', keyword, '%')
       OR `notes` LIKE CONCAT('%', keyword, '%')
    ORDER BY `rating` DESC;
END //

DELIMITER ;



-- ============================================
-- Installation Complete
-- ============================================
SELECT '✅ Johor Food Database Installation Completed!' AS status;
SELECT '📊 Instructions:' AS info;
SELECT '  - View all data: SELECT * FROM johor_food;' AS tips;
SELECT '  - View top-rated food: SELECT * FROM v_high_rating_food;' AS tips;
SELECT '  - View stats by cuisine: SELECT * FROM v_cuisine_stats;' AS tips;
SELECT '  - Query by rating range: CALL sp_get_food_by_rating(4.5, 5.0);' AS tips;
SELECT '  - Query by cuisine: CALL sp_get_food_by_cuisine(''Hunan'');' AS tips;
SELECT '  - Search food: CALL sp_search_food(''Beef'');' AS tips;
